//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USJT.Sigma.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ALUNO
    {
        public int ID_ALUNO { get; set; }
        public Nullable<int> ID_TOPICO { get; set; }
        public string NOM_ALUNO { get; set; }
        public string NUM_CPF { get; set; }
        public string DES_EMAIL { get; set; }
        public System.DateTime DAT_NASCIMENTO { get; set; }
        public string NOM_LOGIN { get; set; }
        public string DES_SENHA { get; set; }
    }
}
