//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USJT.Sigma.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ATIVIDADE_ALUNO
    {
        public int ID_ATIVIDADE_ALUNO { get; set; }
        public int ID_ATIVIDADE { get; set; }
        public int ID_ALUNO { get; set; }
        public Nullable<bool> CHK_STATUS { get; set; }
    
        public virtual TB_ALUNO TB_ALUNO { get; set; }
        public virtual TB_ATIVIDADE TB_ATIVIDADE { get; set; }
    }
}
