//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USJT.Sigma.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ATIVIDADE
    {
        public int ID_ATIVIDADE { get; set; }
        public string NOM_ATIVIDADE { get; set; }
        public string NOM_IMAGEM { get; set; }
        public Nullable<double> VAL_NOTA { get; set; }
        public Nullable<double> QTD_PROGRESSO { get; set; }
    }
}
