//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USJT.Sigma.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CERTIFICADO
    {
        public int ID_CERTIFICADO { get; set; }
        public int ID_ALUNO { get; set; }
        public string DES_URL_CERTIFICADO { get; set; }
    
        public virtual TB_ALUNO TB_ALUNO { get; set; }
    }
}
