//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USJT.Sigma.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TOPICO
    {
        public int ID_TOPICO { get; set; }
        public string NOM_TOPICO { get; set; }
        public string DES_CONTEUDO { get; set; }
    }
}
